/**
 * 通用宏变量
 * 
 * Made By Douzi＂
 */
// 应用环境
export const APP_ENV_DEVELOPMENT = 'dev';
export const APP_ENV_PRODUCTION = 'prod';
// 全局状态
export const APP_STATE_FIELD_KEY_ENV = 'APP_STATE_FIELD_KEY:ENV';
export const APP_STATE_FIELD_KEY_CONF = 'APP_STATE_FIELD_KEY:CONF';
export const APP_STATE_FIELD_KEY_CORE_LOGGER = 'APP_STATE_FIELD_KEY:CORE_LOGGER';
export const APP_STATE_FILED_KEY_SERVICE_CORE = 'APP_STATE_FIELD_KEY:SERVICE_CORE';
export const APP_STATE_FIELD_KEY_MESSAGE_STRUCTOR = 'APP_STATE_FIELD_KEY:MESSAGE_STRUCTOR';
export const APP_STATE_FIELD_KEY_HANDLER_LOGGER_CORE = 'APP_STATE_FIELD_KEY:HANDLER_LOGGER_CORE';
// 状态中心
export const STATE_CENTER_ON_FIELD_CHANGE = 'STATE_CENTER_ON_FIELD_CHANGE';
export const STATE_CENTER_FIELD_CHANGE_TYPE = {
  APPEND: 'STATE_CENTER_FIELD_CHANGE_TYPE_APPEND',
  UPDATE: 'STATE_CENTER_FIELD_CHANGE_TYPE_UPDATE',
  REMOVE: 'STATE_CENTER_FIELD_CHANGE_TYPE_REMOVE',
};
// 返回码
export const RESPONSE_CODE = {
  OTHER: '-1',
  SUCCESS: '0',
  FAILURE: '1',
};
// 日期格式
export const DATE_FORMAT_MILLISECOND = 'YYYY-MM-DD HH:mm:ss.SSS';

